name: astropop

channels:
    - astropy
    - juliotux
    - conda-forge

dependencies:
    - python>=3.7
    - astropy
    - cython
    - matplotlib
    - numpy>=1.16
    - sphinx-astropy
    - pytz
    - pyyaml
    - scikit-image
    - matplotlib
    - scipy
    - astroquery
    - astroscrappy
    - astroalign
    - ccdproc
    - photutils
    - astropy_helpers
    - pip:
        - sep
        - sphinx-rtd-theme
        - sphinxcontrib-apidoc
