# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c
cache:
    directories:
        - $HOME/.astropy/cache
        - $XDG_CACHE_HOME/astropy

os:
    - linux


stage: Comprehensive tests

stages:
   # Do the style check and a single test job, don't proceed if it fails
   - name: Initial tests
   # Test docs, astropy dev, and without optional dependencies
   - name: Comprehensive tests
   # These will only run when cron is opted in
   - name: Cron tests
     if: type = cron


env:
    global:
        # The following versions are the 'default' for tests, unless
        # overridden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NAME="astropop"
        - PYTHON_VERSION=3.7
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - MAIN_CMD='python setup.py'
        - SETUP_CMD='test'
        - EVENT_TYPE='pull_request push'
        - CONDA_ENVIRONMENT='.rtd-environment.yml'
        - CONDA_CHANNELS='astropy juliotux conda-forge'
        - MINICONDA_VERSION=latest
        - FLAKE8_OPT=''

matrix:
    fast_finish: true

    include:
        - stage: Initial tests
          env: SETUP_CMD='egg_info'

        - os: linux
        - stage: Initial tests
          env: SETUP_CMD='test'

        - os: linux
          env: SETUP_CMD='test --coverage'

        - os: linux
          env: SETUP_CMD='build_docs'

        - os: linux
          stage: Cron tests
          env: ASTROPY_VERSION=development NUMPY_VERSION=development EVENT_TYPE='cron'

        - os: linux
          env: PYTHON_VERSION=3.6 NUMPY_VERSION=1.15 SETUP_CMD='test'

        - os: linux
          env: PYTHON_VERSION=3.7 NUMPY_VERSION=1.17 SETUP_CMD='test'

        - os: linux
          env: PYTHON_VERSION=3.8 NUMPY_VERSION=1.17 SETUP_CMD='test'

    allow_failures:
        - os: linux
          stage: Initial tests
          env: MAIN_CMD='flake8 astropop --count --show-source --statistics $FLAKE8_OPT' SETUP_CMD=''

install:
    - source ./ci/travis_setup.sh

script:
  - conda activate $NAME
  - $MAIN_CMD $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == *coverage* ]]; then coveralls --rcfile='astropop/tests/coveragerc'; fi
    - if [[ $SETUP_CMD == *coverage* ]]; then codecov; fi
